export * from './popularNewGamesData'
export * from './newProductGamesData'
export * from './bannerData'
export * from './gameSlidesData'
export * from './upcomingGamesData'
export * from './upcomingGamesListData'
export * from './gameCategories'
