export const postGameDefaultValues = {
  title: '',
  description: '',
  price: 0,
  thumbnails: [],
  category: [],
  tags: [],
  releaseAt: '',
  detailImages: [],
  options: [],
  discountPercentage: 0,
  discountPeriod: { start: '', end: '' },
  detailInfo: {
    contentDescriptors: '폭력성',
    ageRating: 15,
    ratingNumber: 'GC-CC-NP-191115-003',
    ratingDate: '20191115',
    businessName: '주식회사 님블뉴런',
    distributionLicenseNumber: '2013-000005',
    publisher: 'Activision',
    franchise: 'Call of Duty, Black Ops',
    developer: 'Treyarch, Raven Software, Beenox, High Moon Studios',
  },
  recommendedRequirements: {
    os: 'WINDOWS® 10 (64Bit)',
    processor: 'Intel Core i5-6600K , AMD Ryzen 5 1600',
    memory: '16 GB RAM',
    graphics: 'NVIDIA GeForce GTX 1060 , AMD Radeon RX 580 DirectX: 버전 11',
    network: '초고속 인터넷 연결',
    storage: '20 GB 사용 가능 공간',
  },
  minimumRequirements: {
    os: 'WINDOWS® 10 (64Bit)',
    processor: 'Intel Core i3-3225, AMD FX-4350',
    memory: '8 GB RAM',
    graphics: 'NVIDIA GeForce GTX 660, ATI Radeon HD 7850 DirectX: 버전 11',
    network: '초고속 인터넷 연결',
    storage: '15 GB 사용 가능 공간',
  },
}
